### ISSUE TITLE
docker-compose fails to startup the service

### ISSUE THREAD

**Issue by NyakudyaA** [dutchcoders/transfer.sh#194]
# Problem

I have been trying to run the service using docker-compose but I get errors

```
version: '2.1'
services:
   transfer:
      image: dutchcoders/transfer.sh:latest
      ports:
        - "8500:8080"
      restart: on-failure
      environment:
        - provider=local
        - basedir=/tmp/
```
The following is the error

```
transfer_1  | panic: Provider not set or invalid.
transfer_1  | 
transfer_1  | goroutine 1 [running]:
transfer_1  | github.com/dutchcoders/transfer.sh/cmd.New.func2(0xc0000f6dc0)
transfer_1  |   /go/src/github.com/dutchcoders/transfer.sh/cmd/cmd.go:317 +0x1c22
transfer_1  | github.com/dutchcoders/transfer.sh/vendor/github.com/minio/cli.HandleAction(0x8da780, 0xc0001386c0, 0xc0000f6dc0, 0xc000074960, 0x0)
transfer_1  |   /go/src/github.com/dutchcoders/transfer.sh/vendor/github.com/minio/cli/app.go:499 +0x7c
transfer_1  | github.com/dutchcoders/transfer.sh/vendor/github.com/minio/cli.(*App).Run(0xc0000af1e0, 0xc00001e090, 0x3, 0x3, 0x0, 0x0)
transfer_1  |   /go/src/github.com/dutchcoders/transfer.sh/vendor/github.com/minio/cli/app.go:269 +0x600
transfer_1  | github.com/dutchcoders/transfer.sh/vendor/github.com/minio/cli.(*App).RunAndExitOnError(0xc0000af1e0)
transfer_1  |   /go/src/github.com/dutchcoders/transfer.sh/vendor/github.com/minio/cli/app.go:281 +0x53
transfer_1  | main.main()
transfer_1  |   /go/src/github.com/dutchcoders/transfer.sh/main.go:7 +0x32
transfer_transfer_1 exited with code 2
```
What is the difference between running it using docker-compose and running it as a one liner on the terminal.
