### ISSUE TITLE
The LISTENER environment variable isn't working with Docker.

### ISSUE THREAD

**Issue by flavorgold1** [dutchcoders/transfer.sh#481]
It's stuck on port 8080.

How do I change this?

**Comment by stefanbenten** [comment]
Hello @flavorgold1,

the port is fixed inside of the container, see here:
https://github.com/dutchcoders/transfer.sh/blob/b30b296ac838c73a4bcb83e394e6d9dac1b75e27/Dockerfile#L38

In order to map it to a different port you should probably use the docker networking features like this:
`docker run -p 8081:8080 dutchcoders/transfer.sh:latest`

**Comment by flavorgold1** [comment]
I understand that but, I'm in a situation where I have to use `network_mode: host` in `docker-compose.yml`. So, if there's a way through which it can respect that `environment variable`, it'd be great. Thanks anyways.

**Comment by stefanbenten** [comment]
@aspacca I would like your opinion on this.

**Comment by stefanbenten** [comment]
We could make it so that the binary per default listens on 8080 without specifying the flag at all, right?
Then setting the env variable should help, or one needs to pass this flag to the run command. Certainly better than having to maintain custom script solutions.

**Comment by aspacca** [comment]
```
ENTRYPOINT ["/go/bin/transfersh"]
```

```
	cli.StringFlag{
		Name:   "listener",
		Usage:  "127.0.0.1:8080",
		Value:  ":8080",
		EnvVar: "LISTENER",
	},
```

these two changes fixes, only cons: users not specifing a `--listener` flag/`LISTENER` env variable will now bind on every interface instead of localhost only

if we keep `Value:  "127.0.0.1:8080"`, docker won't bind on every interface but only localhost, that's more disruptive probably

**Comment by flavorgold1** [comment]
> https://github.com/dutchcoders/transfer.sh/blob/b30b296ac838c73a4bcb83e394e6d9dac1b75e27/Dockerfile#L38

> if we keep `Value: "127.0.0.1:8080"`, docker won't bind on every interface but only localhost, that's more disruptive probably

The way it is right now, it allows me to access the service via IPv4 and IPv6 directly, with `network_mode: host`. That's a good thing. Please preserve that functionality.

**Comment by flavorgold1** [comment]
This may be a crude solution, but, here's my `docker-compose.yml` file. It is located in `/home/username/transfersh_docker`, along with a `data` directory located in that same directory. It works:

```
version: '3.7'
services:
  transfersh:
    container_name: transfersh
    image: dutchcoders/transfer.sh:latest
    restart: unless-stopped
    user: 1000:1000
    environment:
      - LISTENER=53749
      - BASEDIR=/tmp
      - PROXY_PATH=secretpath
      - PROVIDER=local
      - LOG=/tmp/transfersh.log
      - HTTP_AUTH_USER=username
      - HTTP_AUTH_PASS=password
      - PURGE_INTERVAL=0
      - RANDOM_TOKEN_LENGTH=14
      - MAX_UPLOAD_SIZE=40000000
    entrypoint: "/go/bin/transfersh --listener :53749"
    network_mode: "host"
    volumes:
      - /home/username/transfersh_docker/data:/tmp
```
