### ISSUE TITLE
Provider not set or invalid

### ISSUE THREAD

**Issue by JSBmanD** [dutchcoders/transfer.sh#565]
I was using it with docker-compose.yml but after last update it stopped working.
I have this yml file:

```
version: "3"
services:
  transfer-sh:
    image: dutchcoders/transfer.sh:latest
    command: >
      sh -c "transfer.sh --basedir /tmp/ --provider local --listener :7878"
    ports:
      - 7878:7878
    volumes:
      - /tmp:/tmp
```

But when I start it - I get `Provider not set or invalid.` error

**Comment by aspacca** [comment]
@JSBmanD not sure how it worked before, since there's no `sh` binary in the image (it's based on scratch: only `transfer.sh` binary)


the proper command should be:
```
command: --basedir /tmp/ --provider local --listener :7878
```

**Comment by JSBmanD** [comment]
@aspacca thank you, it worked!

Just for future I'll post ready yml config:
```
version: "3"
services:
  transfer-sh:
    image: dutchcoders/transfer.sh:latest
    command: --basedir /tmp/ --provider local --listener :7878
    ports:
      - 7878:7878
    volumes:
      - /tmp:/tmp
```
