### ISSUE TITLE
Dark mode

### ISSUE THREAD

**Issue by ramonsmits** [dutchcoders/transfer.sh#643]
I searched the code base for text listed on the front page like:

"Easy file sharing from the command line"

and

"Preview your files in the browser!"

but no hits... which is a bit surprising. 

I want to modify the CSS coloring a bit to also support dark mode:

These are some of my current overrides
```css
.body
{
	background-color:black;
	color:silver;
}
#features{
	background-color: #222
}
#reviews{
	background-color: #222
}
```

Where/how is this located in the repo so I can create a PR for it?
